# Generated by Django 4.2.2 on 2024-04-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_options_remove_booking_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
