# Generated by Django 4.2.2 on 2024-05-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
    ]
